### ISSUE TITLE
Custom button to trigger widget

### ISSUE THREAD

**Issue by salimserdar** [Frill-co/frill-widget-examples#1]
Hello there,

I've just implemented a frill widget into the React application.
I'd like to trigger the widget with a custom button instead of the default. And I also want to hide the default one.
[In your example](https://github.com/Frill-co/frill-widget-examples/blob/1015e994fa08486009bb1a914a0fc093dbe4e888/react/src/components/FrillWidget.tsx),  'Click here to show the Widget' button is not trigger my Sidebar widget.

Is there a proper way to do that?

Thank you.

**Comment by mitchheddles** [comment]
Hi @salimserdar

Sorry for the delayed response. When you use a custom trigger you need to make sure you CSS selector in the settings matches your element.

In the example our button has the class name `frill-container`:

```ts
<button type='button' className='frill-container btn'>
```

And our selector is `.frill-container`.
