### ISSUE TITLE
Trigger the opening of a specific tab

### ISSUE THREAD

**Issue by ArmanHashemi** [Frill-co/frill-widget-examples#2]
Dear Developer,

I recently implemented Frill and customized the widget to fit the needs of my web app. However, I am having trouble understanding how to trigger the opening of a specific tab within the widget once a certain button is clicked on my website.

I have looked through the documentation and have not been able to find a solution. Could you please provide guidance on how to do this? Any help would be greatly appreciated.

Thank you,
Arman

**Comment by mitchheddles** [comment]
Hey, we have an example of how to control the widget here https://github.com/Frill-co/frill-widget-examples/blob/master/api/controls.html#L100
